### ISSUE TITLE
Multiple imports of RemoteSwingLibrary with different arguments may hang

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/remoteswinglibrary#12]
If RemoteSwingLibrary is imported with different initialization arguments during the same test run, and the previously connected application has died, the library import can fail or hang.

As a workaround, the library can always be imported with same initial arguments.

**Comment by WojtekKowaluk** [comment]
Fixed by https://github.com/robotframework/remoteswinglibrary/commit/5bb6ca294208c4f6fe4741120884d628818fe743
