### ISSUE TITLE
Running RemoteSwingLibrary with standalone JAR fails on invalid javaagent in JAVA_TOOL_OPTIONS

### ISSUE THREAD

**Issue by lindmik** [robotframework/remoteswinglibrary#15]
When starting a local Java application with a Windows batch script using RemoteSwingLibrary, the java.exe process never starts up.

Robot Framework `log.html` shows on DEBUG level that it sets the `JAVA_TOOL_OPTIONS` to something invalid.

> `Set JAVA_TOOL_OPTIONS='-javaagent:"C:\SUT\__pyclasspath__"=127.0.0.1:57586'`

By looking at the code, it seems like `__file__` is resolved as `__pyclasspath__`, which suggests that this is a Jython issue.

Overriding the `JAVA_TOOL_OPTIONS` in the application's batch script will allow Java to start up, but of course then RemoteSwingLibrary won't be able to connect to it.

**Comment by jussimalinen** [comment]
Actually if you add remoteswinglibrary-2.0.0.jar to JYTHONPATH instead of CLASSPATH it works.

The logic for finding where the jar is doesnt work from CLASSPATH... It is a bug in RemoteSwingLibrary I think, but at least there is a workaround for now.

**Comment by ehhc** [comment]
See my comment here: [#42](https://github.com/robotframework/remoteswinglibrary/issues/42#issuecomment-332866003)
