### ISSUE TITLE
Switch to Application Keyword is not working.

### ISSUE THREAD

**Issue by prasb** [robotframework/remoteswinglibrary#16]
I am trying to connect to a already launched application through Switch to  Application Keyword.

Switch to Application "alias name"
RemoteSwingLibrary.Select Main Window.

The above approach has failed and returned with eroor 
No keyword with name 'RemoteSwingLibrary.Select Main Window' found.

**Comment by mihaiparvu** [comment]
Closing due to no response in a long period of time.
