### ISSUE TITLE
Unable to import Swing libraries into RemoteSwingLibrary

### ISSUE THREAD

**Issue by nmcadam** [robotframework/remoteswinglibrary#21]
Trying to import Swing libraries into RemoteSwingLibrary  fails as custom Swing library seems to be running in local JVM and not remote JVM.

When using RemoteApplications library (which is now deprecated) there was a keyword "Take Libraries Into Use" that allowed you to use custom Swing libraries on remote application.

Having some means of importing custom Swing libraries on remote server would be very useful

**Comment by pekkaklarck** [comment]
Yes, old RemoteApplications did support running arbitrary libraries on the remote JVM. It was mainly used with SwingLibrary, and thus we decided that the new RemoteSwingLibrary only supports, as the name implies, SwingLibrary. The motivation was to make the problem domain smaller, this remote stuff is already complicated enough.

Adding support for other libraries, especially for custom versions of SwingLibrary, is something that can be considered, though. If the library cannot easily support them directly, there could be possibility to build custom RemoteXLibrary that bundles some other library internally. I haven't personally worked with RemoteSwingLibrary much so don't know would that be a big task, but @jussimalinen probably can comment on that one. If the task is non-trivial, and is not needed by our corporate sponsor NSN, it is unlikely that we have resources to implement it in the near future. Pull requests are obviously appreciated also in that case.

**Comment by jussimalinen** [comment]
Yeah, It wouldnt be too difficult to make a base project and instructions on how to bundle your own RemoteXLibrary... but its not trivial either. Unless someone at Nokia requests this, it will take a while before I will have time for that.

**Comment by mihaiparvu** [comment]
[PythonRemoteServer](https://github.com/robotframework/PythonRemoteServer) could be a good starting point for this kind of requests.
