### ISSUE TITLE
Importing 'RemoteSwingLibrary' failed with RobotFramework 2.9rc1

### ISSUE THREAD

**Issue by hedenis** [robotframework/remoteswinglibrary#24]
I get the following when trying to run tests with RemoteSwingLibrary and RF 2.9rc1
```
Error in file 'C:\ROBOT\ROBOT_sandbox\tests\resources.txt': Importing test library 'RemoteSwingLibrary' failed: ImportError: cannot import name GLOBAL_VARIABLES
Traceback (most recent call last): 
File "C:\ROBOT\Jar\remoteswinglibrary-2.0.2.jar\RemoteSwingLibrary.py", line 26, in <module> from robot.variables import GLOBAL_VARIABLES
 PYTHONPATH:
C:\ROBOT\Jar\remoteswinglibrary-2.0.2.jar
 C:\ROBOT\Jar\Lib
 C:\ROBOT\Jar\robotframework-2.9rc1.jar\Lib
 __classpath__ 
__pyclasspath__/ 
CLASSPATH:
***
C:\ROBOT\Jar\remoteswinglibrary-2.0.2.jar
***
C:\ROBOT\Jar\robotframework-2.9rc1.jar
***
```
Could it be a similar issue than rtomac/robotframework-selenium2library#429.

**Comment by pekkaklarck** [comment]
Looks exactly like the referenced Se2Lib bug. Needs to be fixed ASAP, but realistically that happens after next week when @jussimalinen is back from holidays. Before that you have two options:

- Downgrade to RF 2.9 alpha 3 or earlier.
- Try fixing the problem yourself and use the fixed version. If you decided to do this, please submit a pull request too.
