### ISSUE TITLE
running test  with TypeError

### ISSUE THREAD

**Issue by rxw1111** [robotframework/remoteswinglibrary#25]
the log is below:
TEST CASE: Connecting to a started application
Full Name:  Acceptance.Remoteswinglibrary.Connecting to a started application
Start / End / Elapsed:  20150805 13:54:12.483 / 20150805 13:54:12.485 / 00:00:00.002
Status: FAIL (critical)
Message:    TypeError: run_keyword() takes exactly 4 arguments (3 given)
Expand AllKEYWORD: RemoteSwingLibrary.Set Java Tool Options
Documentation:  
Sets the JAVA_TOOL_OPTIONS to include RemoteSwingLibrary Agent.
Start / End / Elapsed:  20150805 13:54:12.484 / 20150805 13:54:12.485 / 00:00:00.001
13:54:12.484    TRACE   Arguments: [  ]
13:54:12.484    FAIL    TypeError: run_keyword() takes exactly 4 arguments (3 given)
13:54:12.485    DEBUG   Traceback (most recent call last):
  None

**Comment by WojtekKowaluk** [comment]
Hello, I can't replicate this issue. Which version of RemoteSwingLibrary and which version of Robot Framework are you using?

**Comment by rxw1111** [comment]
version of RemoteSwingLibrary:2.03
version of Robot Framework:2.8.1
python:2.7.6

**Comment by WojtekKowaluk** [comment]
Robot Framework 2.8.1 is too old. You need at least 2.8.3 .

**Comment by pekkaklarck** [comment]
This version requirement needs to be documented in installation instructions or elsewhere.

**Comment by WojtekKowaluk** [comment]
I have added sentence about it in readme file.

**Comment by rxw1111** [comment]
ok, I will change the version and try again.

**Comment by rxw1111** [comment]
After changing version to 2.9,another error occered. the log is below:

TEST Connecting to a started application
Full Name:	Acceptance.Remoteswinglibrary.Connecting to a started application
Start / End / Elapsed:	20150807 16:21:01.125 / 20150807 16:22:01.147 / 00:01:00.022
Status:	FAIL (critical)
Message:	RemoteSwingLibraryTimeoutError: Agent port not received before timeout
00:00:00.008KEYWORD RemoteSwingLibrary . Set Java Tool Options
00:00:00.007KEYWORD ${handle} = Process . Start Process java org.robotframework.remoteswinglibrary.MySwingApp, shell=True
Documentation:	
Starts a new process on background.
Start / End / Elapsed:	20150807 16:21:01.133 / 20150807 16:21:01.140 / 00:00:00.007
16:21:01.133	TRACE	Arguments: [ 'java org.robotframework.remoteswinglibrary.MySwingApp' | shell='True' ]	
16:21:01.133	INFO	Starting process:
java org.robotframework.remoteswinglibrary.MySwingApp	
16:21:01.133	DEBUG	Process configuration:
cwd = C:\Users\r90004100\Downloads\remoteswinglibrary-master\remoteswinglibrary-master\src\test\robotframework\acceptance
stdout_stream = -1
stderr_stream = -1
shell = True
alias = None
env = None	
16:21:01.140	TRACE	Return: 1	
16:21:01.140	INFO	${handle} = 1	
00:01:00.007KEYWORD RemoteSwingLibrary . Application Started myjava
Documentation:	
Detects new RemoteSwingLibrary Java-agents in applications that are started without
Start / End / Elapsed:	20150807 16:21:01.140 / 20150807 16:22:01.147 / 00:01:00.007
16:21:01.140	TRACE	Arguments: [ 'myjava' ]	
16:22:01.147	FAIL	RemoteSwingLibraryTimeoutError: Agent port not received before timeout	
16:22:01.147	DEBUG	Traceback (most recent call last):
  File "C:\Python27\Lib\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 471, in run_keyword
    return getattr(self, name)(*arguments, **kwargs)
  File "C:\Python27\Lib\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 318, in application_started
    self._application_started(alias, timeout, name_contains, accept_old=True)
  File "C:\Python27\Lib\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 322, in _application_started
    url = self._get_agent_address(name_contains, accept_old)
  File "C:\Python27\Lib\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 343, in _get_agent_address
    raise RemoteSwingLibraryTimeoutError('Agent port not received before timeout')

**Comment by WojtekKowaluk** [comment]
I'm sorry to hear that. Do you have `.java.policy` file? Try creating `.java.policy` file in your home directory with following content:
    grant {
         permission java.security.AllPermission;
    };

**Comment by balak143** [comment]
home directory meaning ? is that the Test Suit Directory of RIDE?

**Comment by WojtekKowaluk** [comment]
No, home directory is your user profile directory.

@rxw1111 Do you still have this problem. Do you mind trying lastest version?

**Comment by baid86** [comment]
Anyupdate on this issue, I am also observing this issue, my robot framework is robotframework==3.0.2 and latest RemoteSwingLibrary.
I only see this issue when I tried to access RemoteSwingLibrary via Remote Interface.

I have started RemoteSwingLibrary using 
```
>>> from robotremoteserver import RobotRemoteServer
>>> from RemoteSwingLibrary import RemoteSwingLibrary
>>> RobotRemoteServer(RemoteSwingLibrary(), host='10.11.198.203')
```
And accessing it in my tests as
```
Library           Remote    http://10.11.198.203:8270
```
