### ISSUE TITLE
Enhancement request: give apport in Start Application keyword

### ISSUE THREAD

**Issue by laurioikarinen** [robotframework/remoteswinglibrary#40]
I would like to ask an enhancement request to Start Application keyword, I would need to give apport in this keyword instead of library import, because:
- When RemoteSwingLibrary is used with multiple UIs in same test, it is not possible to give apport in library import, because it seems that all UIs must have unique port numbers and Switch Application does not actually work if multiple UIs are behind same port.
- Starting UI with Start Application is a bit unstable when used with random port generation (without apport in library import), it fails randomly to "agent port not received before timeout" which I believe is  [this bug](https://github.com/robotframework/remoteswinglibrary/issues/33). The unstability disappears when apport is given in library import, but as stated above, this can't be used with multiple UIs.
- Also [this pull request](https://github.com/robotframework/remoteswinglibrary/pull/39) will not fully work without this enhancement. Connect to application needs to be used with same port number every time and therefore can't be used when multiple UIs are used inside same test suite unless port number can be given in Start Application keyword.

**Comment by WojtekKowaluk** [comment]
Yes, currently `apport` feature and multiple apps feature can't be used at same time. I was thinking about a bit when reviewing pull request from @jakubkorepta , but decided to left it as it is. Now when there is request for it, it should be implemented. However I think we will first release 'apport' feature as it is and this improvement will come with next version. What do you think about this?

**Comment by laurioikarinen** [comment]
Yes, doing things in phases is always a good idea and it's good that you are interested in taking this into consideration.

**Comment by WojtekKowaluk** [comment]
`close_security_dialogs` should also be moved to `Start Application` paramater.
