### ISSUE TITLE
Occasional problem in closing the JWS security dialog

### ISSUE THREAD

**Issue by mvuorenmaa** [robotframework/remoteswinglibrary#50]
This is probably very hard to repeat and investigate. There seems to a quite rare problem in closing the "Do you want to run this application?" confirmation when launching a Java application with Java WebStart.

It's hard to estimate the frequency of the problem without a lot of work spent on it, but it's probably under 0.2% of the launches. I will come back this with more details, if we are able to find any.

We are usually running tests with the newest Java 8 version.

**Comment by mihaiparvu** [comment]
Tried to reproduce it with no luck. Can be reopened if further details are provided.
