### ISSUE TITLE
httplib.BadStatusLine exception when Start Application remotely

### ISSUE THREAD

**Issue by sfrubio** [robotframework/remoteswinglibrary#52]
Using "Start Application" keyword with argument "remote_port", it starts the command line I want, and send it to be executed in a Java agent:
```
    Start Application    Axiodis    javaws -Xnosplash C:\\temp_data\\axiodis.jnlp    timeout=90    name_contains="AXIODIS 6 - Homepage"    remote_port=${REMOTESWINGLIBRARYPORT}
```
This line will trigger a function called "start_application", in "RemoteSwingLibrary.py"
After that, it is executed the function "_application_started", but I'm getting stucked on function "_wait_for_api" triggered by "_application_started", that raises the exception "httplib.BadStatusLine".

In addition, when execute the function "run_keyword" from "Remote.py", it tries to execute the following line:
`return self._server.run_keyword(*run_keyword_args)`
What sounds weird is that "self._server" is a ServerProxy, from xmlrpclib and this object does not contain a method "run_keyword"

**Comment by mihaiparvu** [comment]
As far as I know, "Start Application" keyword can only be used on the host operating system, so you cannot use it to start an application remotely. However, there is a way to do this by relying on the SSHLibrary. 

There is an example [here](https://github.com/robotframework/remoteswinglibrary/blob/master/sshtest.robot), but it's no longer up to date, needs some small tweakings, that I've made below.

``` robotframework
*** Settings ***
Library   SSHLibrary
Library   RemoteSwingLibrary
Resource  ../resource.robot    # outside of repo. Contains real username and password and server IPs

*** Test Cases ***
Connecting to another machine
   Open Connection   ${REMOTEIP}
   Login     ${USERNAME}  ${PASSWORD}
   Put File  ${REMOTESWINGLIBRARYPATH}   remoteswinglibrary.jar
   Write     xvfb-run --auto-servernum java -javaagent:remoteswinglibrary.jar=${MYIP}:APPORT=${REMOTESWINGLIBRARYPORT}:DEBUG -jar myjar.jar
   Application Started    myjar   timeout=5 seconds  remote_host=${REMOTEIP}  remote_port=${REMOTESWINGLIBRARYPORT}
   System Exit
   [Teardown]   Tearing

*** Keywords ***
Tearing
   Read
   Close All Connections
```
