### ISSUE TITLE
Remoteswinglibrary leaks file handles from process wrapper

### ISSUE THREAD

**Issue by PeerMueller** [robotframework/remoteswinglibrary#56]
We have a lot tests (about 1000) that each start two swing applications (using keyword start_application) and shut them down afterwards. 
When running about 100 of them and then starting a new swing application or doing a file operation resulted in "OSError: too many open files" on Windows Server 2008 R2. 

After analysing the issue and monitoring file operations we realized that the remoteswinglibrary creates a new process with two file handles (one for stderr and one for stdout) and does not close them.

I implemented a fix by closing the process wrapper for the current application when keyword system_exit is called which resolved the issue.

**Comment by cristii006** [comment]
Managed to reproduce it by looking at the processes table at OS level. PR #57 correctly fixes the problem.
