### ISSUE TITLE
Implement `Select From List Item Popup Menu` keyword?

### ISSUE THREAD

**Issue by createNull** [robotframework/remoteswinglibrary#69]
Could we have an implementation of this method for List items too?
It's pretty similar to `Select From Table Cell Popup Menu` keyword.

Could be useful for scenarios where components in the app don't have names or labels and they can only be accessed through index.

Thank you in advance!

**Comment by cristii006** [comment]
Hi,

Adding this keyword sounds like a  good idea. It needs to be added in Swing Library and we will try to make it available in the next RemoteSwingLibrary release.

BR,
Cristian

**Comment by mihaiparvu** [comment]
Implemented in https://github.com/robotframework/SwingLibrary/commit/53b0f5ae5fc79b95701129e7fe99291299bd1ef6.
