### ISSUE TITLE
PYTHONPATH is not read correctly in some cases when importing the library

### ISSUE THREAD

**Issue by mihaiparvu** [robotframework/remoteswinglibrary#71]
When performing the check to see if Java version is lower than 9 the following error is thrown in some cases: `Initializing test library 'RemoteSwingLibrary' with no arguments failed: ValueError: could not convert string to float`. I suspect this happens because the pythonpath is not correctly read.

**Comment by badari412** [comment]
Also, the current logic of reading java version may not serve its purpose if the AUT comes with its own custom JRE . As each application will have its own JRE bundled with it, it becomes difficult to develop/run the tests. How about passing the location of Java or "JAVA9_OR_NEWER" as an argument to the __init__ of RemoteSwingLibrary ?

**Comment by mihaiparvu** [comment]
Thank you, this is a very good suggestion. It could avoid a lot of the problems with diffferent environments.

**Comment by filipecduarte** [comment]
Hi have this error too. In my local version i change the org.robotframework.remoteswinglibrary.GetJarLocation.java to:

	public static String getJavaVersion() {

		String version = System.getProperty("java.version");

		if (version.contains(".")) {
			int index = version.indexOf(".");
			index = version.indexOf(".", index + 1);
			return version.substring(0, index);
		}
		return version;
	}

And work fine.

**Comment by filipecduarte** [comment]
I have the same issue, 
i change in my local version of RemoteSwingLibrary.py to import the org.robotframework.remoteswinglibrary.ReadJavaVersion.

And work fine.

**Comment by rasjani** [comment]
Code that tries to locate remoteswinglibrary should also look into robot's commandline parameter "--pythonpath" to check where it might be able to locate the jar. Current implementation looks only for os.environ['PYTHONPATH'] and fails.

**Comment by rasjani** [comment]
possible fix in pr, does not address the issue  @badari412  mentioned ..
