### ISSUE TITLE
No possibility for shift + click on button

### ISSUE THREAD

**Issue by karusha** [robotframework/remoteswinglibrary#76]
Dear RemoteSwingLibrary gurus,

we are using RobotFramework and RemoteSwingLibrary in test automation of our project. 
Really need the possibility to click on button + shift.
I see that it is possible for table cell using Click On Table Cell, would it be possible to add similar functionality for a button?

Many thanks in advance.

**Comment by mihaiparvu** [comment]
Implemented in https://github.com/robotframework/SwingLibrary/commit/53b0f5ae5fc79b95701129e7fe99291299bd1ef6.

**Comment by karusha** [comment]
Many thanks!
