### ISSUE TITLE
 ImportError: No module named RemoteSwingLibrary

### ISSUE THREAD

**Issue by Frogy07** [robotframework/remoteswinglibrary#81]
Hello,
Sorry for a new post because I saw a similar problem but still I cannot solve it. 
I am very beginner in Robot framework and python
When I run file, I cannot import library:
"Importing test library 'RemoteSwingLibrary' failed: ModuleNotFoundError: No module named 'RemoteSwingLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python37-32\Scripts\robot.exe
  c:\python37-32\python37.zip
  c:\python37-32\DLLs                                                                                                     c:\python37-32\lib
  c:\python37-32
  c:\python37-32\lib\site-packages
  c:\python37-32\lib\site-packages\win32
  c:\python37-32\lib\site-packages\win32\lib
  c:\python37-32\lib\site-packages\Pythonwin"

I added c:\python37-32 & c:\python37-32\Scripts to env variables
I added remoteswinglibrary-2.2.3.jar to c:\python37-32\libs

I have installed in versions: 
Python 3.7.2
Robot Framework 3.1.1 (Python 3.7.2 on win32)
pip 19.0.3 from c:\python37-32\lib\site-packages\pip (python 3.7)

I run the robot framework from the command line (Windows) I tried RIDE as well. 

I also installed Selenium2Library using the command line and everything works so I am pretty sure everything is installed properly.
I noticed RF is looking for library in "c:\python37-32\lib\site-packages"

I have wasted too much time and I am stuck.  I have no idea what can I do better. You are my last hope to solve this problem :)

**Comment by Costallat** [comment]
Try using/adding the full path to the jar file:

"robot --pythonpath c:\python37-32\libs\remoteswinglibrary-2.2.3.jar  <test folder>"
