### ISSUE TITLE
So the app is started but then the error appear

### ISSUE THREAD

**Issue by mel-exerp** [robotframework/remoteswinglibrary#85]
20:04:43.178 | INFO | Failed to start application: Traceback (most recent call last): File "C:\xxxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 433, in start_application self._application_started(alias, timeout, name_contains, remote_port, accept_old=False) File "C:\xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 485, in _application_started self._wait_for_api(url) File "C:\xxx\remoteswinglibrary-2.2.4.jar\RemoteSwingLibrary.py", line 472, in _wait_for_api raise RuntimeError('Connecting to api at %s has failed: %s' % (url, error)) RuntimeError: Connecting to api at 127.0.0.1:42145 has failed: ''

**Comment by T970222** [comment]
did you found solution for it?
