### ISSUE TITLE
Is there any method to connet the applet with (remote )swing library

### ISSUE THREAD

**Issue by constantine97a** [robotframework/remoteswinglibrary#86]
Dear mihaiparvu :

There is a very very old applet application that we need to  robot it .
But I had found no method to connect it and drive it.
For example :
1 I click button on web
2 The browser redirect me to another url , that URL will trigger the applet application to startup .
3 So How could I robot that applet application
Could you please give me a hint or some guide ? 

Thanks

**Comment by mihaiparvu** [comment]
This issue tracker is for bug reports and enhancement requests. Questions are best asked on mailing lists, Slack (`#swinglibrary` channel), or other such support forums listed at http://robotframework.org. 

As for your question, as far as I can tell you could use a combination of SeleniumLibrary keywords (for the web part) and RemoteSwingLibrary (`Start Application` keyword) for the applet (but only if the application has its GUI coded in Java Swing). In any case, this disscution should be continued in the support forums I previously mentioned.
