### ISSUE TITLE
RemoteSwingLibrary UNEXPECTED INTERNAL ERROR In Swing application when using "Start Application" keyword

### ISSUE THREAD

**Issue by Zaki-2** [robotframework/remoteswinglibrary#94]
I'm trying to test a Swing application with RemoteSwingLibrary 
Environment:
 OS:
     Windows 10, 64-Bit
     java version "11.0.5" 2019-10-15 LTS
     Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
     Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)
     Robot Framework 3.1.2 (Python 3.7.7 on win32)
 Swing Application:
     openjdk version "11.0.5" 2019-10-15
     OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
     OpenJDK Client VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
RemoteSwingLibrary 2.2.6
I can connect and Interact to the application using RemoteSwingLibrary, but when the application is in step open application i get This Exception:
################################################################################
# UNEXPECTED INTERNAL ERROR 
# java.lang.NoSuchMethodError: 'void org.eclipse.jetty.servlet.ServletHolder.<init>(javax.servlet.Servlet)'

19.10.20 17:17:46.041 <main>         [SEVERE]  >> Wincash.start():                                    'void Org.eclipse.jetty.servlet.ServletHolder.<init>(javax.servlet.Servlet)' |   |  
-- | -- | --
  | java.lang.NoSuchMethodError: 'void org.eclipse.jetty.servlet.ServletHolder.<init>(javax.servlet.Servlet)' |   |  
  | at nts.application.websocket.customer.bouyfr.listener.StartWebSocketStepListener.perform(StartWebSocketStepListener.java:88) |   |  
  | at nts.application.wincash.controller.base.AbstractStepListener.eventPerformed(AbstractStepListener.java:51) |   |  
  | at nts.infrastructure.extention.ControllerEventRegistry.fireSpecificEvents(ControllerEventRegistry.java:92) |   |  
  | at nts.infrastructure.extention.ControllerEventRegistry.fireEvent(ControllerEventRegistry.java:75) |   |  
  | at nts.infrastructure.controller.BusinessController.fireExecutionEvents(BusinessController.java:891)

`
*** Settings ***
Library    RemoteSwingLibrary   debug=True  port=3000
Library    ImageHorizonLibrary
Library    Process

*** Test Cases ***
Open APP
    [Arguments]   ${pathToLauncher}=C:/Users/Public/myApp/jbin/launcher.jar
    ...          ${pathToAppLaunch}=C:/Users/Public/myApp/jbin/app-launch.xml
    ...          ${java}=C:/Users/Public/myApp/jbin/jre/bin/java.exe
    RemoteSwingLibrary.Start Application    myApp  ${java} -jar ${pathToLauncher} ${pathToAppLaunch}
    RemoteSwingLibrary.Select Main Window
`
![image](https://user-images.githubusercontent.com/11617832/96499262-7898e580-124d-11eb-93b3-ad999f5913c5.png)

when I run manually the same command (${java} -jar ${pathToLauncher} ${pathToAppLaunch}) from the command line Everything works well (No Exception)

Can anyone help on this issue?
Thank you in advance

**Comment by karusha** [comment]
Hi, 
actually I'm having the same issue, raised another ticket regarding this #96.
I guess workaround is going to be exclude jar which has class from Jetty from classpath.

**Comment by mihaiparvu** [comment]
Any chance you @karusha or @Zaki-2 are working on an open-source app so that can I test myself? As I didn't have any success reproducing this locally on my environment.

**Comment by mihaiparvu** [comment]
Closing until new info is available.

**Comment by Zaki-2** [comment]
Hello @mihaiparvu,
Sorry for my late response,
unfortunately I don't work on open-source app , but I can give you some elements if you want !
15 / 5000
Résultats de traduction
thanks in advance
